# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19MGoC3S4IV2oIEU4IOn2lSCYShfqTI7j
"""

import streamlit as st
st.title("Web Based Aspect-based sentiment analysis for earphone and headset")
input = st.text_input("Enter the review you want")
result = pipe_lr.predict([input])
btn = st.button("Predict")
if btn:
  st.text(result)